// Code generated by Embedder. DO NOT EDIT.

package internal

const (
	// Source: resources/FlashBagIndex.html
	FlashBagIndex = `H4sIAAAAAAAC/2yPwUrGMBCE7z7FsHjOT6/S9iAoCN5UPMd00wTKBpJIDyHvLmlpEf6e9mNndpYp
BRNbLwwyQTJLJtT6AACl4NEuOrkfPeNpwMnqcPSuG0uB+vR5YdTa31w33t2qj19jOCVQ2uHyg3oT
G0BebLjWv3UULzNo3eHa9RJjiCBu479j9dlBvQejl2O7NdBwke1AWw1O+Ss2ncbGeG2peNZzf9Nn
L5apJZz0FwAA//8Gs1VAQgEAAA==`
)
