// Code generated by Embedder. DO NOT EDIT.

package internal

const (
	// Source: resources/FlashBagIndex.html
	FlashBagIndex = `H4sIAAAAAAAC/2yPsWoDMRBEe3/FsKSWcRvOVxgSSG1DauW8uhOIVZB0pFj234NsYgK+ah/MY9hR
xZVDFAZNWRpLI5jtAEAVLyH5unz5Ga9HPNjBrIdrSecpf3MP15Kqe+/Gyc9/DcNyGFXhLrElhtmw
Xw7jU7c7r9PEtYLqHTY/cB8SMihKyNv5py8SZQb93GHbeislFxD38zAGj6VwONL/Ve7CtcGMxhvc
tuHk52Hvx50qWK4w+w0AAP//V5Sya0ABAAA=`
)
