// Code generated by Embedder. DO NOT EDIT.

package internal

const (
	// Source: resources/FlashBagIndex.html
	FlashBagIndex = `H4sIAAAAAAAC/2yPQWsDIRCF7/0VD+nZkGvZ7CHQQqG3BHq2ZlwFGYu65CDz34sbsix0T374Ho/5
WsONXGCCsokrcVUQeQGA1vDqoin+x0x4O2FlDZEezjlebPqlHs45Fv3RG2czPRcGfxxbg76GGgki
w8Efx3/b+jJbS6VAlQfsXqA/2SWowC7t598mc+AJ6v6A/dZ7zilDUX+2jXuoHvorWROfv4uBgc/k
Tmrrq69UKkTUuMBijbOZhoNZ7YhvfWelvwAAAP//Nrv8v2gBAAA=`
)
