// Code generated by Embedder. DO NOT EDIT.

package internal

const (
	// Source: resources/VueAlert.html
	VueAlert = `H4sIAAAAAAAC/0yPwWrDMBBE7/6KQZdciv0DtqGHFpprv2BrbZwNimy0a0EQ+fciG9ocR6OZfVMK
PF8kMty0RONoDs9nAwC9lwzxg8sbvwdO5sb9fffW8euCx7KBEkOZJc6wqyjurEozv0HsVBVF3f9d
KXM8GebFcKZM31OS1fAR6Sew77v1KO87L3lsSgFHX0maF8IbZdI99w95aNhj5cHdF78FdtA0Da4U
bClo+ymBtT3/ZVEHdVQXtTetTW7su8N7ufwbAAD//5Bsn7waAQAA`
)
