// Code generated by Embedder. DO NOT EDIT.

package internal

const (
	// Source: resources/Error.html
	Error = `H4sIAAAAAAAC/1zOQQrCQAwF0L2n+PQA9QKlK90pCHqBMJPqoGRKGnER5u4ijDqaVZL/Ft8dkack
jC5kMRbrUMoKANzxSHZBv8uBbu9vTdIEyYZ+q7oho/6gOd6DpSwtfM0wj+5fuOdloTOjlGE9j39S
+ccejcL1pBQqVx7bDiyx6Vqvz/YMAAD//6amXRPaAAAA`
)
