// +build debug

// Code generated by MockGen. DO NOT EDIT.
// Source: flash_bag.go

package view

import (
	reflect "reflect"

	ctx "github.com/cjtoolkit/ctx/v2"
	gomock "github.com/golang/mock/gomock"
)

// MockFlashBagView is a mock of FlashBagView interface
type MockFlashBagView struct {
	ctrl     *gomock.Controller
	recorder *MockFlashBagViewMockRecorder
}

// MockFlashBagViewMockRecorder is the mock recorder for MockFlashBagView
type MockFlashBagViewMockRecorder struct {
	mock *MockFlashBagView
}

// NewMockFlashBagView creates a new mock instance
func NewMockFlashBagView(ctrl *gomock.Controller) *MockFlashBagView {
	mock := &MockFlashBagView{ctrl: ctrl}
	mock.recorder = &MockFlashBagViewMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockFlashBagView) EXPECT() *MockFlashBagViewMockRecorder {
	return m.recorder
}

// ExecIndex mocks base method
func (m *MockFlashBagView) ExecIndex(ctx ctx.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ExecIndex", ctx)
}

// ExecIndex indicates an expected call of ExecIndex
func (mr *MockFlashBagViewMockRecorder) ExecIndex(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecIndex", reflect.TypeOf((*MockFlashBagView)(nil).ExecIndex), ctx)
}
