// Code generated by Embedder. DO NOT EDIT.

package internal

const (
	// Source: resources/Index.html
	Index = `H4sIAAAAAAAC/7RSTYucQBC97694NIGcnD4ke1kcD7skkJBbAjn3dJdjZ7VbumomDuJ/DxoH4mwv
Oa0Xy/dBvSprHOGo9oGgbAxCQRSKaboDgHHEu1NqGQ97LO9puluIsq9+UmtjR5CIp6/vGbGnUHA8
JUugoafkOwqyK3VfrR7nz7CtYd6rFH+jk+KjqhbqlraxLTpXfPiHfiExyd3QOUlxiO6S0S3a5n4j
FS8tqepza7jBozniB7GUurl/xd5v3TSIqmaLD0eYlpKALyzU4XABm/MMS0NwRsy8tblmYvYxwASH
RJb8RpVtOz+mFkpI5Hwiu+44G9GgSVTv1fVH7pbhHs1x9yU4GjBNajNE68Ozqkp/BWvDqM0V1r7C
Nx+eS23+068R6flB66OX5nTY2dhp+4uGXtcpBtGSiHRnWCjpek30aehzWV7dwYuQNjpaQ37/e4ZP
0VE+Z26AUjt/vjm4LXT7mb3YNxGt5TiCgsM0/QkAAP//F5M1HbUDAAA=`
)
